Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,29 +2,24 @@ name: Automated Commit
 
 on:
   push:
-    branches: [master] # Ensures the workflow triggers on pushes to master
-
+    branches: [master] # Trigger trên nhánh master
   schedule:
-    - cron: '*/10 * * * *' # Executes every 10 minutes
-
-  workflow_dispatch: # Allows manual triggering from the GitHub UI
+    - cron: '*/10 * * * *' # Chạy mỗi 10 phút
+  workflow_dispatch: # Trigger thủ công từ GitHub UI
 
 permissions:
-  contents: write # Grants permissions to write to the repo
+  contents: write # Cấp quyền ghi cho repository
 
 jobs:
   update_commit:
-    runs-on: ubuntu-latest # Specifies the runner
+    runs-on: ubuntu-latest # Sử dụng runner Ubuntu
 
     steps:
-      - name: Setup Debug Information
-        run: echo "::debug::Triggered by ref = ${{github.ref}}"
-
       - name: Checkout Code
-        uses: actions/checkout@v3 # Latest version for optimized performance
+        uses: actions/checkout@v3 # Dùng action checkout
         with:
-          persist-credentials: true # Ensures credentials are available for subsequent steps
-          fetch-depth: 0 # Fetches all history for all branches and tags
+          persist-credentials: true # Giữ lại thông tin đăng nhập GitHub
+          fetch-depth: 0 # Lấy toàn bộ lịch sử commit
 
       - name: Update Timestamp File
         run: |
@@ -36,6 +31,10 @@ jobs:
           git config user.email "dinhnhatminh.minhkhanh@gmail.com"
           git config user.name "linux-vps"
 
+      - name: Pull Latest Changes
+        run: |
+          git pull origin master --rebase || echo "No updates to pull."
+
       - name: Prepare Commit
         run: |
           commit_messages=("Update: ⏰" "Refresh: 🔄" "Renew: 🌟" "Revise: 📝" "Amend: 🛠" "Adjust: 🔧" "Change: 📈" "Modify: 🖊" "Transform: 🌀" "Revamp: 🌈")
@@ -44,8 +43,6 @@ jobs:
           git add TIMESTAMP.txt
           git commit -m "$random_msg - $current_time" || echo "No changes to commit."
 
-      - name: GitHub Push
-        uses: ad-m/github-push-action@v0.6.0
-        with:
-          directory: '.'
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push Changes
+        run: |
+          git push origin master || echo "Push failed. Retry after manual review."
